language: python
python:
  - "3.5"
install:
  # command to install dependencies
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  # install self
  - python setup.py develop
script:
  - py.test
